### PR TITLE
Support formData in server validation

### PR DESCRIPTION
**Pull request by kentcdodds**
This is an incomplete PR. Please feel free to take it all the way. I just thought it would be more helpful than an issue 😅

### CODE REVIEW

**Comment by chaance** [comment]
I think in many cases you'll want `formData.get("whatever")` instead of the field's current value, since validation is async and the error message will show the wrong value while the next validation runs. This could solve that nicely!

**Comment by brophdawg11** [comment]
Good call @chaance - looks like there's a bit of a bug in re-generating the custom error message using the new value while old validations are pending.  Going to file a separate issue for that

**Comment by brophdawg11** [comment]
^^ https://github.com/brophdawg11/remix-validity-state/issues/20

**Comment by brophdawg11** [comment]
Just released this in `0.6.0` 👍

**Comment by kentcdodds** [comment]
Thank you!

**Pull request merged**
